### ISSUE TITLE
Rename z/VM Cloud Connector to Feilong in docs

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/feilong#364]
Currently the documentation still references z/VM Cloud Connector - probably should update to Feilong

**Comment by bjhuangr** [comment]
@jichenjc do not forget to trigger a new readthedocs build after the change merged.

**Comment by bjhuangr** [comment]
The doc has been updated:
https://cloudlib4zvm.readthedocs.io/en/latest/
