### ISSUE TITLE
Consider updating copyright and license notices to match OMP TAC recommendations

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/feilong#365]
The TAC has recommended SPDX usage and simplified copyright notices for it's hosted projects ( see https://github.com/openmainframeproject/tac/blob/master/process/contribution_guidelines.md#license-specification ). We are seeing larger usage of this pattern as well outside of OMP project ( https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/ ).

For this project, the recommendation would be to change headers to this for code...

```python
#  Copyright Contributors to the Feilong Project.
#  SPDX-License-Identifier: Apache-2.0
```
and this for documentation
```markdown
#  Copyright Contributors to the Feilong Project.
#  SPDX-License-Identifier: CC-BY-4.0
```

There are numerous files with IBM copyright notices; if they are to be removed it must be by an IBM employee.

Let me know of any questions/concerns.

**Comment by jmertic** [comment]
@mfriesenegger @jichenjc Bump

**Comment by jichenjc** [comment]
@jmertic sorry, didn't notice this :( 
will check what we can do and let you know

**Comment by bjhuangr** [comment]
https://github.com/openmainframeproject/feilong/pull/703
