### ISSUE TITLE
Error with client api call after upgrade

### ISSUE THREAD

**Issue by HeraldtenDam** [openmainframeproject/feilong#440]
I had Feilong 1.4 running and wanted to upgrade. 1th I took the latest version, so now I have version 1.6, but also has an error, although on the same call but different message. I show the 1.6 version now.

I have a guest TEST6, not running. I want to show his definition by running http://CC-server/guests/TEST6
The error is: "Unexpected internal error in ZVM SDK, error: Could not find the userid: Unexpected internal error in ZVM SDK, error: Command \"sudo vmcp q TEST6\" Error: __init__() got an unexpected keyword argument 'timeout'"

Calling sudo on command line gives: 
**sudo vmcp q TEST6**
HCPCQU045E TEST6 not logged on
Error: non-zero CP response for command 'Q TEST6': #45

smcli works:
/**opt/zthin/bin/smcli Image_Query_DM -T test6**
USER TEST6 LBYONLY 1024M 2G G
INCLUDE LINUXFEI
COMMAND DEF STOR RESERVED 1024M
CPU 00 BASE
IPL CMS
MACHINE ESA 4
MDISK 0100 FB-512 138600032 25165824 LNXOS5 MW
MDISK 1300 9336 81760160 2097152 LNXOS6 MR
MDISK 1301 9336 1200032 20480 LNXOS1 MR
*DVHOPT LNK0 LOG1 RCM1 SMS0 NPW1 LNGAMENG PWC20201030 CRCXX

I made zthin and sdkserver from this 1.6 version.
Running Feilong on Suse 15 SP1.

**Comment by jichenjc** [comment]
thanks for report this, some questions, I think it's weird because this `GET` is widely used in our solution so less likely it has such issue

I assume you have backtrace or you can find at zvmsdk logs (/var/log/zvmsdk/*.log) ? or in the console? 
it will be easier to check what's inside the callback and know the reason

**Comment by HeraldtenDam** [comment]
Hi, just did the test again, this is the logging:

[2021-04-02 10:27:04] [DEBUG] [Thread-1] (127.0.0.1:43044) Request func: guest_get_definition_info, args: [u'TEST6'], kwargs: {}
[2021-04-02 10:27:04] [ERROR] [Thread-1] (127.0.0.1:43044) Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zVMCloudConnector-1.4.0-py2.7.egg/zvmsdk/sdkserver.py", line 150, in serve_API
    return_data = api_func(*api_args, **api_kwargs)
  File "/usr/lib/python2.7/site-packages/zVMCloudConnector-1.4.0-py2.7.egg/zvmsdk/api.py", line 62, in inner
    self._vmops.check_guests_exist_in_db(userids)
  File "/usr/lib/python2.7/site-packages/zVMCloudConnector-1.4.0-py2.7.egg/zvmsdk/vmops.py", line 437, in check_guests_exist_in_db
    if zvmutils.check_userid_on_others(uid):
  File "/usr/lib/python2.7/site-packages/zVMCloudConnector-1.4.0-py2.7.egg/zvmsdk/utils.py", line 584, in check_userid_on_others
    raise exception.SDKInternalError(msg=msg)
SDKInternalError: Unexpected internal error in ZVM SDK, error: Could not find the userid: Unexpected internal error in ZVM SDK, error: Command "sudo vmcp q TEST6" Error: __init__() got an unexpected keyword argument 'timeout'

**Comment by jichenjc** [comment]
I gave a try and you are right, this was introduced at commit dc532f751 and the param is introduced recently 

it works for python3 but doesn't work for python2 (I knew we had a python2 test but not sure why it's not covered), given python2 is already not supported for one year, do you think it's ok to upgrade to python3?
if not , I think as workaround you can edit zvmsdk/utils.py and upgrade

```
def execute(cmd, timeout=None):
    """ execute command, return rc and output string.
    The cmd argument can be a string or a list composed of
    the command name and each of its argument.
    eg, ['/usr/bin/cp', '-r', 'src', 'dst'] """

    # Parse cmd string to a list
    if not isinstance(cmd, list):
        cmd = shlex.split(cmd)
    # Execute command
    rc = 0
    output = ""
    try:
        output = subprocess.check_output(cmd, close_fds=True,
                                         stderr=subprocess.STDOUT,
                                         timeout=timeout) 

```

to 
```
def execute(cmd, timeout=None):
    """ execute command, return rc and output string.
    The cmd argument can be a string or a list composed of
    the command name and each of its argument.
    eg, ['/usr/bin/cp', '-r', 'src', 'dst'] """

    # Parse cmd string to a list
    if not isinstance(cmd, list):
        cmd = shlex.split(cmd)
    # Execute command
    rc = 0
    output = ""
    try:
        output = subprocess.check_output(cmd, close_fds=True,
                                         stderr=subprocess.STDOUT)

```

```
root@jjtest1:~/python-zvm-sdk# python2
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> cmd = "ls"
>>> subprocess.check_output(cmd, close_fds=True,
...                                          stderr=subprocess.STDOUT,
...                                          timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
>>>
root@jjtest1:~/python-zvm-sdk# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> cmd = "ls"
>>> subprocess.check_output(cmd, close_fds=True,
...                                          stderr=subprocess.STDOUT,
...                                          timeout=1)
b'CODE_OF_CONDUCT.md\nCONTRIBUTING.md\ndata\ndco_signoffs\ndoc\nfeilong_meetings\nfvt-requirements.txt\nGOVERNANCE.md\nLICENSE\nMAINTAINERS.txt\nMANIFEST.in\nREADME.md\nrequirements.txt\nrhel-8.3-update-2-x86_64-kvm.qcow2?user=80a03f9ed45b1399a40860f4a9e85663\nsample\nscale_test\nscripts\nsetup.py\nsmtLayer\nspecs\ntest-requirements.txt\ntools\ntox.ini\nwget-log\nzthin-parts\nzVMCloudConnector.egg-info\nzvmconnector\nzvmsdk\n'

```

**Comment by HeraldtenDam** [comment]
Thanks for the reply, you are right, we should think of an upgrade to Python3. I will have a look at it.
If the upgrade worked, I wanted to upgrade also some customer Feilong servers, so this will take some more time.

**Comment by jichenjc** [comment]
if so , do you think ok to close this issue and reopen if needed later? Thanks

**Comment by HeraldtenDam** [comment]
Hi,

I updated to Python3 (1th server) and now it works. So for me issue is closed, now I can use the latest version.
