### ISSUE TITLE
sdkserver.service failed to start up when no FCP devices found

### ISSUE THREAD

**Issue by hjieyang** [openmainframeproject/feilong#675]
I got the following error when I tried to bring up the sdkserver service.  There are no FCP devices on my VM system.  The smapi SYSTEM_WWPN_QUERY call returned RC=4 (warning return code) with an empty output buffer, but the exception on the python layer was taken due to RC<>0.  It looks to me that RC=4 from the SYSTEM_WWPN_QUERY call should not prevent sdkserver from up running. 

[root@linux076 zvmsdk]# vmcp q fcp all
An active FCP was not found.
A free FCP was not found.
An offline FCP was not found.
An FCP Agent was not found.

[root@linux076 zvmsdk]# journalctl -u sdkserver
Aug 30 16:33:19 linux076.lvn.broadcom.net systemd[1]: Started zVM SDK API server.
Aug 30 16:33:45 linux076.lvn.broadcom.net sudo[4093]:   zvmsdk : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/vmcp query userid
Aug 30 16:33:46 linux076.lvn.broadcom.net sudo[4097]:   zvmsdk : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/vmcp query userid
Aug 30 16:33:47 linux076.lvn.broadcom.net sudo[4101]:   zvmsdk : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/vmcp query userid
Aug 30 16:33:47 linux076.lvn.broadcom.net sudo[4105]:   zvmsdk : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/zthin/bin/smcli System_WWPN_Query --addRCheader -T LINUX076 -k OWNER=YES
Aug 30 16:33:49 linux076.lvn.broadcom.net python3.6[4085]: detected unhandled Python exception in '/usr/local/bin/sdkserver'
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]: Traceback (most recent call last):
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/utils.py", line 421, in log_and_reraise_smt_request_failed
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     yield
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/smtclient.py", line 291, in get_fcp_info_by_status
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     results = self._request(rd)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/smtclient.py", line 140, in _request
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     raise exception.SDKSMTRequestFailed(results, msg)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]: zvmsdk.exception.SDKSMTRequestFailed: SMT request failed. RequestData: 'getvm LINUX076 fcpinfo all YES', Results: '{'overallRC': 8, 'rc': 4, 'rs': 28, 'errno': 0, 'strErro>
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]: During handling of the above exception, another exception occurred:
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]: Traceback (most recent call last):
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/bin/sdkserver", line 4, in <module>
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     __import__('pkg_resources').run_script('zVMCloudConnector==1.6.3', 'sdkserver')
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self.require(requires)[0].run_script(script_name, ns)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     exec(code, namespace, namespace)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/EGG-INFO/scripts/sdkserver", line 24, in <module>
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     sdkserver.start_daemon()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/sdkserver.py", line 264, in start_daemon
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     server = SDKServer()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/sdkserver.py", line 42, in __init__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self.sdkapi = api.SDKAPI()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/api.py", line 99, in __init__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self._volumeop = volumeop.get_volumeop()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 60, in get_volumeop
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     _VolumeOP = VolumeOperatorAPI()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 85, in __init__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     VolumeOperatorAPI._fcp_manager_obj = FCPVolumeManager()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 1666, in __init__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self.fcp_mgr = FCPManager()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 478, in __init__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self.sync_db()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 487, in sync_db
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self._sync_db_with_zvm()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 914, in _sync_db_with_zvm
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     fcp_dict_in_zvm = self.get_fcp_dict_in_zvm()
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 799, in get_fcp_dict_in_zvm
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     fcp_dict_in_zvm = self.get_all_fcp_pool(smt_userid)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 738, in get_all_fcp_pool
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     all_fcp_info = self._get_all_fcp_info(assigner_id)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/volumeop.py", line 490, in _get_all_fcp_info
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     fcp_info = self._smtclient.get_fcp_info_by_status(assigner_id, status)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/smtclient.py", line 291, in get_fcp_info_by_status
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     results = self._request(rd)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     self.gen.throw(type, value, traceback)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:   File "/usr/local/lib/python3.6/site-packages/zVMCloudConnector-1.6.3-py3.6.egg/zvmsdk/utils.py", line 428, in log_and_reraise_smt_request_failed
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]:     raise exception.SDKSMTRequestFailed(err.results, msg)
Aug 30 16:33:51 linux076.lvn.broadcom.net sdkserver[4085]: zvmsdk.exception.SDKSMTRequestFailed: Failed to query fcp info of 'LINUX076'. SMT error: SMT request failed. RequestData: 'getvm LINUX076 fcpinfo all YES', Results: '{'ove>
Aug 30 16:33:51 linux076.lvn.broadcom.net systemd[1]: sdkserver.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 16:33:52 linux076.lvn.broadcom.net systemd[1]: sdkserver.service: Failed with result 'exit-code'.

Thanks
Hongjie Yang

**Comment by bjhuangr** [comment]
@dongyanyang please help to comment, thanks

**Comment by jichenjc** [comment]
@hjieyang which version are u using (we have env that doesn't have FCP at all, it works fine) so want to know whether it's a bug already fixed recently or a new issue related to VMSecure + zcc. thanks

**Comment by hjieyang** [comment]
Ji Chen, I checked out the feilong code on 8/12/2022.  The following "git log" responses show most recent commits.  Thanks.

[root@linux076 ~]# ls -l
total 8
-rw-------.  1 root root 2374 Aug 25  2019 anaconda-ks.cfg
drwxr-xr-x. 20 root root 4096 Aug 12 13:30 feilong
-rw-r--r--.  1 root root    0 Aug 29 12:21 iucvselx.te
drwxr-xr-x.  2 root root   33 Jul 24  2020 tmp_leapp_py3
[root@linux076 ~]# cd feilong
[root@linux076 feilong]# git branch
* master
[root@linux076 feilong]# git log
commit 878f7c1153e3b7fa9072906bcc7de4ab7e3e8022 (HEAD -> master, origin/master, origin/HEAD)
Author: xingjing <xingjing@cn.ibm.com>
Date:   Tue Jul 26 15:34:18 2022 +0800

    bug fix
    1. move acquire lock out of try-catch
    2. update a method name in _rollback_dedicated_fcp

    Signed-off-by: xingjing <xingjing@cn.ibm.com>

commit 8dffbf6571f0f0dfb6e24ee46bfa7e322153ba71
Author: xingjing <xingjing@cn.ibm.com>
Date:   Mon Jul 25 14:06:57 2022 +0800

    Update per Donggyan's comments

    Signed-off-by: xingjing <xingjing@cn.ibm.com>

commit 7e493c4143afce23edcb39b1d01eb3569744527d
Author: xingjing <xingjing@cn.ibm.com>
Date:   Thu Jul 21 18:13:46 2022 +0800

    add UT

    Signed-off-by: xingjing <xingjing@cn.ibm.com>

**Comment by jichenjc** [comment]
ok, so the code is new enough, @dongyanyang might help on this topic,

**Comment by dongyanyang** [comment]
@hjieyang Could you please help to collect the following info for us to check? Thanks!

1. The output of cmd:
`smcli System_WWPN_Query -T $(vmcp q userid | awk '{print $1}') --addRCheader`

2. run `systemctl restart sdkserver` on your server and then share us the two log files: /var/log/zvmsdk/smt.log and /var/log/zvmsdk/zvmsdk.log

**Comment by jichenjc** [comment]
@hjieyang please check whether https://github.com/openmainframeproject/feilong/pull/677 can help you ?
just patch in your system and share whether it's ok to you?

**Comment by hjieyang** [comment]
Ji Chen and Dong yangyang, after applying the fix 677, my sdkserver is up running successfully.  Thanks.
