### ISSUE TITLE
API call GetGuestInfo() returns a float instead of an int for max_mem_kb

### ISSUE THREAD

**Issue by Bischoff** [openmainframeproject/feilong#766]
## What happens

According to the Feilong 1.6.5 documentation:
```
max_mem_kb	body	integer	The maximum memory in KBytes can be allocated for this guest.
```
However Feilong returns value `4194304.0`, which is not an integer, but a floating point number, in case of a maximum memory of 4 GiB.

This produces an error when you try to unmarshal that value.

## What should happen

`GetGuestInfo() ` should return an integer for field `max_mem_kb`.

The other field `mem_kb` is an integer as expected.

**Comment by jichenjc** [comment]
reasonable request to me , we will check with folks and see whether it's an old bug or regression introduced recently

**Comment by jichenjc** [comment]
https://github.com/openmainframeproject/feilong/blob/master/zvmsdk/vmops.py#L112
this has (int) force but this doesn't
https://github.com/openmainframeproject/feilong/blob/master/zvmsdk/vmops.py#L136

can you add (int) in front of line 136 and see whether it fix the problem?

**Comment by bjhuangr** [comment]
@Bischoff Was the guest in power off state? when getting the info.

**Comment by Bischoff** [comment]
Thanks for the quick replies.

| can you add (int) in front of line 136 and see whether it fix the problem?

I will ask to the person who deployed the Feilong instance, I currently do not have access to this machine. I will get back to you.

| @Bischoff Was the guest in power off state? when getting the info.

As far as I can remember, yes. I can do a second test while powered on.

**Comment by Bischoff** [comment]
@bjhuangr Indeed, after the guest is powered on, I get an integer as expected.

**Comment by Bischoff** [comment]
The process advertised in `CONTRIBUTING.md` does not work for me, I get:
```
$ git review get-guest-info-max-mem-kb-type
git : 'review' n'est pas une commande git. Voir 'git --help'.
```

I will do a more "regular" PR here, without this GerritHub thing.

**Comment by Bischoff** [comment]
Here is my PR: https://github.com/openmainframeproject/feilong/pull/768

**Comment by bjhuangr** [comment]
@Bischoff thanks for attempting to submit a PR to fix this. If the gerrit process not work for you, you can just submit the PR with general github process.

**Comment by Bischoff** [comment]
ok, doing that, thanks @bjhuangr .

**Comment by Bischoff** [comment]
Merge please? ...

**Comment by Bischoff** [comment]
Thank you.
